#ifndef VOICEMEETER_UI_DEFINITIONS_LOADER_H
#define VOICEMEETER_UI_DEFINITIONS_LOADER_H

#define IDT_HLSL 256
#define IDT_BIT 257
#define IDR_HLSL_PIXEL 101
#define IDR_HLSL_VERTEX 102
#define IDR_BIT_ATLAS 103

#endif
