#ifndef _ATLAS_H_
#define _ATLAS_H_

#define _ATLAS_BLOCK_W 26
#define _ATLAS_BLOCK_H 17

#define ATLAS_W 8 * _ATLAS_BLOCK_W 
#define ATLAS_H 14 * _ATLAS_BLOCK_H

#define ATLAS_KNOB_FRAME_X 4 * _ATLAS_BLOCK_W
#define ATLAS_KNOB_FRAME_Y 0 * _ATLAS_BLOCK_H
#define ATLAS_KNOB_FRAME_W 48
#define ATLAS_KNOB_FRAME_H 48
#define ATLAS_KNOB_INDICATOR_X 6 * _ATLAS_BLOCK_W
#define ATLAS_KNOB_INDICATOR_Y 0 * _ATLAS_BLOCK_H
#define ATLAS_KNOB_INDICATOR_W 6
#define ATLAS_KNOB_INDICATOR_H 6

#define ATLAS_PLUG_FRAME_X 6 * _ATLAS_BLOCK_W
#define ATLAS_PLUG_FRAME_Y 1 * _ATLAS_BLOCK_H
#define ATLAS_PLUG_FRAME_W 41
#define ATLAS_PLUG_FRAME_H 19

#define ATLAS_VBAN_FRAME_X 0 * _ATLAS_BLOCK_W
#define ATLAS_VBAN_FRAME_Y 0 * _ATLAS_BLOCK_H
#define ATLAS_VBAN_FRAME_W 39
#define ATLAS_VBAN_FRAME_H 22

#endif
